// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @notice Generated by deployment script. Do not edit manually.
library TrapDeployConfig {
    address internal constant REGISTRY = 0x0000000000000000000000000000000000003001;
    address internal constant RESPONSE = 0x0000000000000000000000000000000000000000;
    bytes32 internal constant ENVIRONMENT_ID = keccak256("bonqdao-oracle-manipulation-trap-mainnet");
}
